import json
import os
import numpy as np
import matplotlib.pyplot as plt

base_dir = os.path.dirname(os.path.abspath(__file__))
results_path = os.path.join(base_dir, "pilot_results.json")

print("Loading results...")
with open(results_path, "r", encoding="utf-8") as f:
    results = json.load(f)

data = results["data"]["conditions"]

def get_stats(cond_name):
    cond_data = data[cond_name]
    return {
        "raw_test": cond_data["test_accuracies"],
        "raw_densities": cond_data["prompt_densities"],
        "raw_tokens": cond_data["net_tokens"]
    }

base = get_stats("stateless_baseline")
rag = get_stats("vector_rag")
rar = get_stats("rar_compressed")

plt.style.use('seaborn-v0_8-paper')
plt.rcParams['font.family'] = 'serif'
plt.rcParams['mathtext.fontset'] = 'dejavuserif'
plt.rcParams['font.size'] = 10

# Fig 2 Boxplots + Tradeoffs
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))
ax1.grid(True, linestyle='--', alpha=0.6)
ax1.boxplot([base["raw_test"], rag["raw_test"], rar["raw_test"]], labels=['Baseline', 'Vector RAG', 'RAR (Compressed)'])
ax1.set_title(r"$\mathbf{Test\ Vault\ Accuracies\ (N=10\ Seeds)}$", fontweight='bold')
ax1.set_ylabel("Strict Test Accuracy", fontweight='bold')

ax2.grid(True, linestyle='--', alpha=0.6)
x = np.arange(3)
densities_mean = [np.mean(base["raw_densities"]), np.mean(rag["raw_densities"]), np.mean(rar["raw_densities"])]
tokens_mean = [np.mean(base["raw_tokens"]), np.mean(rag["raw_tokens"]), np.mean(rar["raw_tokens"])]

ax2.bar(x - 0.2, densities_mean, width=0.35, label="Context Density", color='#1c4f8a')
ax2.set_ylabel(r"Mean Context Density ($\delta$)", fontweight='bold')
ax2.set_xticks(x)
ax2.set_xticklabels(['Baseline', 'Vector RAG', 'RAR'])
ax2.set_title(r"$\mathbf{Context\ and\ Token\ Tradeoffs}$", fontweight='bold')

ax2_twin = ax2.twinx()
ax2_twin.bar(x + 0.2, tokens_mean, width=0.35, label="Net Tokens", color='#b41e1e')
ax2_twin.set_ylabel("Net Tokens (chars)", fontweight='bold')

ax2.legend(loc='upper left', bbox_to_anchor=(0.0, -0.15))
ax2_twin.legend(loc='upper right', bbox_to_anchor=(1.0, -0.15))
plt.tight_layout()
plt.savefig(os.path.join(base_dir, "fig2_crs_trajectory.png"), dpi=300)
plt.close()

# Fig 3 density comparison
plt.figure(figsize=(7, 4.5))
plt.grid(True, linestyle='--', alpha=0.6)
plt.bar(['Baseline', 'Vector RAG', 'RAR'], densities_mean, color=['#b41e1e', '#1c4f8a', '#2ca02c'])
plt.ylabel(r"Mean Context Density ($\delta$)", fontweight='bold')
plt.title(r"$\mathbf{Empirical\ Context\ Density\ comparison}$", fontweight='bold')
plt.tight_layout()
plt.savefig(os.path.join(base_dir, "fig3_density.png"), dpi=300)
plt.close()

# Fig 5 degradation
delta = np.linspace(0, 1.5, 100)
q = np.where(delta <= 0.5, 1.0, np.where(delta <= 0.9, 1.0 - (delta - 0.5) / 0.4, 0.0))
plt.figure(figsize=(8, 5))
plt.plot(delta, q, color='black', linewidth=2)
plt.fill_between(delta, q, color='blue', alpha=0.1)
plt.scatter([0.5, 0.9], [1.0, 0.0], color='red', zorder=5)
plt.text(0.5, 1.05, r'$\delta_{low}=0.5$', ha='center')
plt.text(0.9, -0.05, r'$\delta_{high}=0.9$', ha='center')
plt.axvline(0.58, color='gray', linestyle='--')
plt.text(0.6, 0.8, r'$\epsilon=0.80$ ($	au=0.58$)', verticalalignment='bottom')
plt.xlabel('Context Density ($\delta$)')
plt.ylabel('Proposal Quality $q(\delta)$')
plt.title('Context-Rot Degradation Model')
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig(os.path.join(base_dir, "fig5_degradation.png"), dpi=300)
plt.close()

print("Correct visual assets successfully regenerated by generate_graphs.py!")
